version: '3'

services:
 prelistingDB:
    image: postgres:15.3
    container_name: prelisting-db
    restart: always
    ports:
      - 5432:5432

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data